name: 0:Terraform + Bootstrapping

on: workflow_dispatch

jobs:
  Terraform-Bootstrapping:
    runs-on: self-hosted
    steps :
      - uses: actions/checkout@v2
      - name: Terraform + Bootstrapping
        working-directory: ./terraforms
        continue-on-error: true
        id: terraform-apply
        run: |
          terraform -chdir=web-server init
          terraform -chdir=db-server init
          nohup terraform -chdir=db-server apply -lock=false --auto-approve -var-file="db-server.tfvars" &
          terraform -chdir=web-server apply -lock=false --auto-approve -var-file="web-server.tfvars"

  # Web デプロイエラー時にクリーンアップを実行する。
      - name: Cleanp 
        if: steps.terraform-apply.outcome != 'success'
        run: |
          terraform apply -destroy --auto-approve -var-file="web-server.tfvars"
          knife node list -c .chef/config.rb | grep "demo" | xargs knife node delete -y -c .chef/config.rb
          knife client list -c .chef/config.rb | grep "demo" | xargs knife client delete -y -c .chef/config.rb