name: 0:Terraform + Bootstrapping

on: workflow_dispatch

jobs:
  Terraform-Apply-Bootstrapping:
    runs-on: self-hosted
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Running Terraform
        run: |
          terraform -chdir=terraforms/web-server init & terraform -chdir=terraforms/db-server init
          terraform -chdir=terraforms/web-server apply --auto-approve -var-file="web-server.tfvars" & terraform -chdir=terraforms/db-server apply --auto-approve -var-file="db-server.tfvars"
