name: 0:Terraform + Bootstrapping

on: workflow_dispatch

jobs:
  Terraform-Bootstrapping-WEB:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./terraforms/web-server
    steps :
      - uses: actions/checkout@v2
      - name: Running Terraform
        continue-on-error: true
        id: terraform-apply-web
        run: |
          terraform init
          terraform apply --auto-approve -var-file="web-server.tfvars"
  
  # デプロイエラー時にクリーンアップを実行する。
      - name: Cleanp 
        if: steps.terraform-apply-web.outcome != 'success'
        run: |
          terraform apply -destroy --auto-approve -var-file="web-server.tfvars"
          knife node list -c .chef/config.rb | grep "demo" | xargs knife node delete -y -c .chef/config.rb
          knife client list -c .chef/config.rb | grep "demo" | xargs knife client delete -y -c .chef/config.rb
  
  Terraform-Bootstrapping-DB:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./terraforms/db-server
    steps :
      - uses: actions/checkout@v2
      - name: Running Terraform
        continue-on-error: true
        id: terraform-apply-db
        run: |
          terraform init
          terraform apply --auto-approve -var-file="db-server.tfvars"
  
  # デプロイエラー時にクリーンアップを実行する。
      - name: Cleanp 
        if: steps.terraform-apply-db.outcome != 'success'
        run: |
          terraform apply -destroy --auto-approve -var-file="db-server.tfvars"
          knife node list -c .chef/config.rb | grep "demo" | xargs knife node delete -y -c .chef/config.rb
          knife client list -c .chef/config.rb | grep "demo" | xargs knife client delete -y -c .chef/config.rb
