name: 2:Destroy All Instances

on: workflow_dispatch

jobs:     
  Terraform-Cleanup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cleanp 
        working-directory: ./terraforms/web-server
        run: terraform apply -destroy --auto-approve -var-file="web-server.tfvars"

  Chef-Cleanup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cleanp 
        run: |
          knife node list -c .chef/config.rb | grep "demo" | xargs knife node delete -y -c .chef/config.rb
          knife client list -c .chef/config.rb | grep "demo" | xargs knife client delete -y -c .chef/config.rb